openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /v1/users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  children:
                    type: array
                    items:
                      oneOf:
                        - type: string
                          minLength: 3
                          maxLength: 20
                        - type: integer
                        - $ref: "#/components/schemas/IString"
                        - $ref: "#/components/schemas/INumber"
                    oneOf:
                      - minItems: 0
                        maxItems: 20
              examples: # Child of media type
                Jessica: # Example 1
                  value:
                    id: 10
                    name: Jessica Smith
                    children: Horst
                Ron: # Example 2
                  value:
                    id: 11
                    name: Ron Stewart
                    children: Hilde

        "204": # status code
          description: A error string

        "500": # status code
          description: A error string
          content:
            application/json:
              schema:
                type: string
    post:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/orderDetailsResponse"
components:
  schemas:
    orderDetailsResponse:
      type: object
      additionalProperties: false
      properties:
        vertriebsauftragsNummer:
          $ref: '#/components/schemas/IString'
        auftragsDatum:
          $ref: '#/components/schemas/IString'
        bestelltyp:
          $ref: '#/components/schemas/IString'
        benutzerId:
          $ref: '#/components/schemas/IString'
        bezugsArt:
          $ref: '#/components/schemas/IString'
        herkunft:
          $ref: '#/components/schemas/IString'
        lieferant:
          $ref: '#/components/schemas/IString'
        exportStatus:
          $ref: '#/components/schemas/IString'
        auftraggeber:
          $ref: '#/components/schemas/IString'
        bestellreferenz:
          $ref: '#/components/schemas/IString'
        warenkorbId:
          $ref: '#/components/schemas/IString'
        debug:
          $ref: '#/components/schemas/IBool'
    IString:
      type: object
      additionalProperties: false
      properties:
        value:
          type: string
        type:
          type: string
          enum:
            - 'string'
      required:
        - value
        - type

    INumber:
      type: object
      additionalProperties: false
      properties:
        value:
          type: integer
        type:
          type: integer
      required:
        - value
        - type

    IBool:
      type: object
      additionalProperties: false
      properties:
        value:
          type: boolean
        type:
          type: string
          enum:
            - "boolean"
        hidden:
          type: boolean
      required:
        - value
        - type